version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incidentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  incident-service:
    container_name: incident-service
    build:
      context: ./IncidentService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=incidentdb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    volumes:
      - incident_images:/app/wwwroot/images/incidents  # ✅

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    depends_on:
      - incident-service
      - moderation-service  # ✅ Dodajte i ovu zavisnost

  moderation-service:
    build:
      context: ./ModerationService
      dockerfile: Dockerfile
    container_name: moderation-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6001:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - incident_images:/app/wwwroot/images/incidents  
    
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
    ports:
      - "7000:8080"

volumes:
  postgres_data:
  incident_images: