services:
  incident-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5048:80"

  api-gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
  moderation-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6001:8080"   
  user-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "7000:8080" 
